#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json
test_format = 1.0

[default]

    exclude = [ "install.nourl" ]

    test_upgrade_from.99330d46e45662b922de84e2e48ad1b15a63bb6e.name = "v1.6.7~ynh1"
    test_upgrade_from.f16db30b1108870417f42e758da358a47df8c290.name = "v1.6.12~ynh1"
